### ISSUE TITLE
PurgeSiteLog does nothing if portal's SiteLogHistory setting is set to 0

### ISSUE THREAD

**Issue by jbrinkman** [DNNCommunity/Dnn.SiteLog#1]
The scheduler PurgeSiteLog does nothing if the portal's SiteLogHistory setting is set to 0.

IMHO the scheduler should remove the existing site log records even if SiteLogHistory is set to 0. Imagine the scenario where the site log was enabled (SiteLogHistory > 0) for some time and site log records were created and the admin disabled the site log by setting SiteLogHistory = 0. With the current implementation the scheduler would not remove the existing records.

I will create a pull request to fix this problem.

This issue was migrated from [DNN-7245](https://dnntracker.atlassian.net/browse/DNN-7245)

**Comment by cathalconnolly** [comment]
I assume you know about https://github.com/dnnsoftware/Dnn.Platform/pull/639

**Comment by jbrinkman** [comment]
Yes.

**Comment by valadas** [comment]
I cannot reproduce this issue with current code, if still reproducible after 8.0.1 (tonight or in a few days) release, please open a new issue.
