### ISSUE TITLE
How do I configure SiteLog to exclude a url when hitting my dnn home page?

### ISSUE THREAD

**Issue by shash99** [DNNCommunity/Dnn.SiteLog#10]
We have an "out of band" monitor that consistently checks our site for load balancing.  It fills the SiteLog table.   Can I configure the SiteLog to ignore incoming Url's?

**Comment by valadas** [comment]
No, this module currently does not exclude anything. I suggest you point your monitor to the KeepAlive.aspx file wich does not get tracked.
