### ISSUE TITLE
SiteLog Not Working After 8.00 Install

### ISSUE THREAD

**Issue by brads99** [DNNCommunity/Dnn.SiteLog#12]
I migrated a DNN 7 Community site to DNN 8 Community Site and the SiteLog stopped collecting data and displayed message "Your Hosting Provider Has Disabled the Site Log History Feature For Your Website." on the SiteLog page.

I installed DNNCE_SiteLog_08.00.00_Install.zip, which installed without errors, but the SiteLog entries in the HostSettings table were not inserted.  I manually inserted them using T-SQL based upon the entries in my last DNN 7 backup.  I also inserted them into the PortalSettings table as well, even though they were not in my DNN 7 PortalSettings table.

I also checked the Schedule table on DNN 8 and there is a "Dnn.Modules.SiteLog.Components.PurgeSiteLog, Dnn.Modules.SiteLog" setting, which is different than "DotNetNuke.Services.Log.SiteLog.PurgeSiteLog, DOTNETNUKE" on DNN 7.  I am assuming that this is due to the fact that SiteLog was removed from DNN core and made into its own module.

I know that some of the User Interface pieces are missing, so I am very comfortable updating the database manually, if you can give me some guidance as to where to look.  I have restarted the site several times.  Thanks for your assistance.

**Comment by brads99** [comment]
Does anyone have any ideas on how to hot fix this issue?  Thanks - Brad

**Comment by brads99** [comment]
I now have this working on www.BoxfordCableTv.com website.  I first followed muddeatr's advice in Issue #8 to insert a SettingValue for SitLogHistory in PortalSettings table.  Once I did this, log entries started being inserted, but **without** the userid.

I then followed the trail in Issue #7.  I downloaded the source, made the changes that klaaspolinder did in Fix #11 to SiteLogModule.cs and rebuilt the dll using VS 2017 Community Edition.  (I did need to add 3 external references to the project, but overall very easy for a C# software engineer like myself.)  

If you want a copy of the rebuilt Dnn.Modules.SiteLog.dll, comment on this issue with an email address.  I will give you FTP info to download the dll.

**Comment by valadas** [comment]
It would be awesome if you could submit that as a pull request instead @brads99

**Comment by brads99** [comment]
Dan - I have never used GitHub (I'm a VSS / TFS user), so if you can guide me through what I need to do with some specific details, I will be happy to do this.

I will say that when I downloaded the latest source, the changes that klaaspolinder committed at some point after Jul 27, 2017 were not in the source code.  At that point I realized I did not fully understand the process involved in dealing with GitHub.

Who is responsible for building a new install zip?

**Comment by valadas** [comment]
@brads99 I made a video series on how to contribute to the various Dnn repositories, you can see that at https://www.youtube.com/watch?v=zLB6uzdqGF8&list=PLIx1M8IdVvqZ0bnODGqJyxvONNPj5BzMP
If you are already familiar with .Net tooling and Dnn, then I suggest watching the 3rd one that shows a bit how github works and the 4th one has an example on submitting a pull request for a module (such as this one). And if you are uncertain about something, just let me know and I can help.

As for building the install package, for a module it would be the repository official maintainer, this one has no official maintainer so someone on the team will need to build it and make it available, I will be happy to do it, I honestly thought that the underlying infrastructure to support this module features was removed, but if you confirm it is working, awesome, I will be happy to merge the two existing Pull Requests and yours and publish a new release.

**Comment by brads99** [comment]
Thanks!  This is definitely working!  I will try get to this in the next 48 hours.

**Comment by brads99** [comment]
Dan - Maybe the correct thing to do is rebuild the project using klaaspolinder's pull request from 2017?  I just copied his 2 changes and that resolved the issue.

**Comment by valadas** [comment]
@brads99 I just merged a pull request that should make it easier to build this project, so basically you can now just clone, open in Visual Studio, build in release mode and you will get an install package in the Install folder.

This being said, are you sure this still works on Dnn 8, I think there is no more site settings UI to enable and configure the site log...

**Comment by valadas** [comment]
@brads99 scratch my last comment, I just merged a pull request that brings the settings UI into the module settings since it no longer exists in the site settings. This should solve this issue, I am closing it but you can still comment, so if after trying the 8.0.1 release you still have this issue, feel free to comment or open a new issue.
