### ISSUE TITLE
Not able to set site log history

### ISSUE THREAD

**Issue by DLFergrd** [DNNCommunity/Dnn.SiteLog#4]
This modlue used to use settings from the Host Settings page. It no longer has this.
It requres a settings page to enable the functionality of the module.

**Comment by sleupold** [comment]
settings used to be on Site Settings page, but anyway - the module needs a UI for setting the following PortalSettings values: SiteLogHistory, SiteLogBuffer and SiteLogStore (database or file system)

**Comment by DLFergrd** [comment]
I did create a UI for those settings. There is currently a pull request in for it.

**Comment by sleupold** [comment]
Thanks, I need to find out, who is the owner of this project to get it reviewed and pulled.

**Comment by RockSolidSW** [comment]
Hey guys, was there ever any progress made to get that pull request baked into a copy of the module?  Todd

**Comment by valadas** [comment]
I am processing the existing pull requests and processing issues that are bugs for a last Dnn 8 compatible release, then we need to think for Dnn 9, I would be willing to convert this into a persona bar module, but that is only if the feature still works in Dnn 9 and with performance and GDPR considerations... I will open up an issue for discussing this after I finish with this last fix release for Dnn 8. Please watch for an 8.0.1 release in the next following days @RockSolidSW and @DLFergrd
