### ISSUE TITLE
No UserId in Sitelog results

### ISSUE THREAD

**Issue by ghost** [DNNCommunity/Dnn.SiteLog#7]
exec sp_executesql N';Exec dbo.AddSiteLog @0, @1, @2, @3, @4, @5, @6, @7, @8, @9',N'@0 datetime,@1 int,@2 nvarchar(4000),@3 nvarchar(4000),@4 nvarchar(4000),@5 nvarchar(4000),@6 nvarchar(4000),@7 nvarchar(4000),@8 int,@9 nvarchar(4000)',@0='2016-04-10 17:28:17.870',@1=0,@2=NULL,@3=N'http://domain.com/.../www.../Default.aspx... (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0',@6=N'83.162.224.165',@7=N'83.162.224.165',@8=128,@9=NULL

**Comment by minimomo** [comment]
same issue here.
What I do is to modify SiteLogModule.cs, change BeginRequest to AuthorizeRequest. Not sure if this is the right solution, anyway it works.

**Comment by valadas** [comment]
Fixed by #11
